title: Raúl Penagos Solórzano
logo: /assets/img/logo.jpg
email: raul.penagos@hotmail.es
description: Portfolio
favicon: true
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: CV
    icon: <i class="fa-solid fa-file-pen"></i>
    link: ./assets/files/Raul_Penagos_CV.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/RaulPenagos
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/ra%C3%BAl-penagos-sol%C3%B3rzano-920648324/
  # - name: Projects
  #   icon: <i class="fa-solid fa-bars-progress"></i>
  #   link: ./projects
  # - name: Educational Physics Portfolio (Spanish)
  #   icon: <i class="fa-solid fa-pen-clip"></i>
  #   link: https://sites.google.com/upr.edu/yarelisacevedo
